"""Build a self-contained example HTML page from a saved scenario run.

The output is committed to `examples/example_scenario.html` and viewed via
htmlpreview.github.io so a GitHub visitor can see a real scenario without
running anything locally.

Usage:
    python scripts/build_example_page.py <run_id> [--out examples/example_scenario.html]
"""
from __future__ import annotations

import argparse
import base64
import json
import os
import sys
from typing import Any, Dict

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, ROOT)

from app import db  # noqa: E402


HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Cold War Scenario Simulator &mdash; Example Run</title>
  <style>__STYLE__</style>
</head>
<body>
  <header class="topbar">
    <div class="brand">
      <div class="brand-mark"></div>
      <div>
        <h1>Cold War Scenario Simulator</h1>
        <p class="subtitle">
          Multi-agent geopolitical scenario planning for USA&ndash;China rivalry, 2026&ndash;2031
        </p>
      </div>
    </div>
    <div class="model-pill" id="modelPill">example run</div>
  </header>

  <main class="layout" style="grid-template-columns: 1fr;">
    <section class="content">
      <div class="panel" style="background: rgba(76,139,245,0.08); border-color: #2a4a8a;">
        <strong>This is a static example of one real scenario run.</strong>
        <span class="muted small">
          &nbsp;Generated by the multi-agent pipeline (Orchestrator + Evidence/RAG + 5 domain agents + Red-Team)
          and rendered exactly as the live dashboard would. Source repo:
          <a href="https://github.com/shaimove/second_cold_war" style="color:#9bb6e6;">shaimove/second_cold_war</a>.
        </span>
      </div>

      <div id="result" class="result">
        <header class="result-header">
          <h2 id="scenarioTitle"></h2>
          <span id="statusBadge" class="badge"></span>
        </header>
        <p id="scenarioSummary" class="summary"></p>

        <div class="panel">
          <h3>Seed</h3>
          <p id="seed" class="muted"></p>
        </div>

        <section class="panel">
          <h3>Timeline 2026&ndash;2031</h3>
          <div id="timeline" class="timeline"></div>
        </section>

        <div class="grid-2">
          <section class="panel">
            <h3>Agent discussion</h3>
            <div id="discussion"></div>
          </section>
          <section class="panel">
            <h3>Agent summaries</h3>
            <div id="agentSummaries"></div>
          </section>
        </div>

        <div class="grid-2">
          <section class="panel">
            <h3>Main disagreements</h3>
            <ul id="disagreements" class="bullets"></ul>
          </section>
          <section class="panel">
            <h3>Red-team warnings</h3>
            <ul id="redTeam" class="bullets"></ul>
          </section>
        </div>

        <section class="panel image-panel">
          <h3>Generated illustration</h3>
          <div id="imageBox" class="image-box"></div>
          <details class="prompt-details" open>
            <summary>Image prompt</summary>
            <p id="imagePrompt" class="muted small"></p>
          </details>
        </section>

        <section class="panel">
          <h3>Run metrics</h3>
          <div id="metrics" class="metrics"></div>
        </section>
      </div>
    </section>
  </main>

  <script>
    const DATA = __DATA__;
    const IMAGE_URL = "__IMAGE__";
    __RENDERER__
    render(DATA, IMAGE_URL);
  </script>
</body>
</html>
"""


RENDERER_JS = r"""
function $(s) { return document.querySelector(s); }
function escapeHtml(s) {
  if (s == null) return "";
  return String(s)
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}
function render(data, imageUrl) {
  $("#scenarioTitle").textContent = data.scenario_title || "(untitled scenario)";
  $("#scenarioSummary").textContent = data.scenario_summary || "";
  $("#seed").textContent = data.seed || "";
  const badge = $("#statusBadge");
  badge.textContent = data.event_status || "hypothetical";
  badge.className = "badge " + (data.event_status || "hypothetical");

  const tl = $("#timeline"); tl.innerHTML = "";
  (data.timeline || []).forEach((yb) => {
    const card = document.createElement("div");
    card.className = "year-card";
    const events = (yb.events || []).map((ev) => {
      const prob = (ev.probability != null) ? (Math.round(ev.probability * 100) + "%") : "—";
      return (
        '<div class="event">' +
          '<div>' + escapeHtml(ev.event || "") + '</div>' +
          '<div class="event-meta">' +
            '<span class="tag">' + escapeHtml(ev.domain || "") + '</span>' +
            '<span class="tag impact-' + escapeHtml(ev.impact || "medium") + '">impact: ' + escapeHtml(ev.impact || "") + '</span>' +
            '<span class="tag confidence-' + escapeHtml(ev.confidence || "medium") + '">conf: ' + escapeHtml(ev.confidence || "") + '</span>' +
            '<span class="tag">p=' + prob + '</span>' +
          '</div>' +
          '<div class="muted small">' + escapeHtml(ev.rationale || "") + '</div>' +
        '</div>'
      );
    }).join("");
    card.innerHTML =
      '<div class="year">' + escapeHtml(String(yb.year)) + '</div>' +
      '<div class="headline">' + escapeHtml(yb.headline || "") + '</div>' +
      (events || '<div class="muted small">No events.</div>');
    tl.appendChild(card);
  });

  const disc = $("#discussion"); disc.innerHTML = "";
  (data.discussion_summary || []).forEach((r) => {
    const block = document.createElement("div");
    block.className = "round-block";
    const agree = (r.areas_of_agreement || []).map(escapeHtml).join(" · ") || "—";
    const disagree = (r.areas_of_disagreement || []).map(escapeHtml).join(" · ") || "—";
    const uncert = (r.key_uncertainties || []).map(escapeHtml).join(" · ") || "—";
    block.innerHTML =
      '<div class="label">Round ' + escapeHtml(String(r.round_number || "?")) + '</div>' +
      '<div class="row"><strong>Agree:</strong> ' + agree + '</div>' +
      '<div class="row"><strong>Disagree:</strong> ' + disagree + '</div>' +
      '<div class="row"><strong>Uncertain:</strong> ' + uncert + '</div>';
    disc.appendChild(block);
  });

  const summaries = $("#agentSummaries"); summaries.innerHTML = "";
  const order = ["geo_strategy", "economy_technology", "domestic_ideology", "security_taiwan", "historical_analogy", "red_team"];
  const map = data.agent_summaries || {};
  order.forEach((k) => {
    if (!map[k]) return;
    const div = document.createElement("div");
    div.className = "agent-card";
    div.innerHTML = '<div class="name">' + escapeHtml(k.replace(/_/g, " ")) + '</div><div>' + escapeHtml(map[k]) + '</div>';
    summaries.appendChild(div);
  });

  function fillList(sel, items) {
    const root = $(sel); root.innerHTML = "";
    if (!items.length) { root.innerHTML = '<li class="muted">None.</li>'; return; }
    items.forEach((x) => { const li = document.createElement("li"); li.textContent = x; root.appendChild(li); });
  }
  fillList("#disagreements", data.main_disagreements || []);
  fillList("#redTeam", data.red_team_warnings || []);

  const box = $("#imageBox"); box.innerHTML = "";
  if (imageUrl) {
    const img = document.createElement("img");
    img.src = imageUrl;
    img.alt = "Generated illustration";
    box.appendChild(img);
  } else {
    box.innerHTML = '<div class="placeholder"><strong>No image available.</strong></div>';
  }
  $("#imagePrompt").textContent = data.image_prompt || "(no prompt)";

  const m = data.run_metrics || {};
  const metricsRoot = $("#metrics"); metricsRoot.innerHTML = "";
  [
    ["LLM calls", m.llm_calls],
    ["Cache hits", m.cache_hits],
    ["Retrieved docs", m.retrieved_docs],
    ["Rounds completed", m.discussion_rounds_completed],
    ["Elapsed (s)", m.elapsed_seconds],
    ["Est. in tokens", m.estimated_input_tokens],
    ["Est. out tokens", m.estimated_output_tokens],
    ["Agents used", (m.agents_used || []).length],
  ].forEach(([k, v]) => {
    const d = document.createElement("div");
    d.className = "metric";
    d.innerHTML = '<div class="k">' + escapeHtml(k) + '</div><div class="v">' + escapeHtml(String(v == null ? "—" : v)) + '</div>';
    metricsRoot.appendChild(d);
  });
}
"""


def build(run_id: str, out_path: str) -> None:
    payload = db.load_scenario_run(run_id)
    if payload is None:
        raise SystemExit("run not found: " + run_id)

    style_path = os.path.join(ROOT, "frontend", "style.css")
    with open(style_path, "r", encoding="utf-8") as fh:
        style = fh.read()

    out_dir = os.path.dirname(out_path) or "."
    os.makedirs(out_dir, exist_ok=True)

    # Copy the generated image next to the HTML so the bundled page stays
    # small (htmlpreview.github.io resolves relative URLs correctly).
    image_ref = ""
    img_path = (payload.get("image") or {}).get("path")
    if img_path and os.path.exists(img_path):
        ext = os.path.splitext(img_path)[1] or ".png"
        local_name = "example_image" + ext
        with open(img_path, "rb") as src, open(
            os.path.join(out_dir, local_name), "wb"
        ) as dst:
            dst.write(src.read())
        image_ref = local_name

    html = (
        HTML_TEMPLATE
        .replace("__STYLE__", style)
        .replace("__DATA__", json.dumps(payload, ensure_ascii=False))
        .replace("__IMAGE__", image_ref)
        .replace("__RENDERER__", RENDERER_JS)
    )
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(html)
    print(
        "Wrote " + out_path + " (" + str(len(html)) + " bytes)"
        + (", image: " + image_ref if image_ref else "")
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("run_id")
    parser.add_argument("--out", default="examples/example_scenario.html")
    args = parser.parse_args()
    build(args.run_id, args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
